version: '3.8'

services:
  db:
    image : postgres:17.5-alpine3.22
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: master-golang
      POSTGRES_USER: vixuancu
      POSTGRES_PASSWORD: 123456
    ports: 
      - "5433:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
