# giới hạn tối đa trên RAM
maxmemory 256mb

# least recently used : khi bộ nhớ đạt tới 256mb , redis sẽ xóa key nào có TTL (Time To Live : thời gian sống của 1 key , tính bằng giây) gần hết hạn và ít dùng nhất 
maxmemory-policy volatile-lru

# Bật persistence (RDB) để lưu dữ liệu
save 900 1 # Lưu dữ liệu mỗi 15 phút nếu có ít nhất 1 key thay đổi
save 300 10 # Lưu dữ liệu mỗi 5 phút nếu có ít nhất 10 key thay đổi
save 60 10000 # Lưu dữ liệu mỗi phút nếu

dir /data