
-- câu lệnh sql thì viết hoa còn lại thì viết thường
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
-- create table
CREATE TABLE IF NOT EXISTS users (
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	user_email VARCHAR(100) UNIQUE NOT NULL,
	user_password VARCHAR(90) NOT NULL,
	user_fullname VARCHAR(90) NOT NULL,
	user_age INT CHECK (user_age >= 1 AND user_age <= 120),
	user_status INT NOT NULL DEFAULT 1 CHECK (user_status IN (1, 2, 3)),
	user_level INT NOT NULL DEFAULT 1 CHECK (user_level IN (1, 2, 3)),
	user_deleted_at TIMESTAMPTZ DEFAULT NULL,
	user_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	user_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
--comment on column: create comment
COMMENT ON COLUMN users.user_status IS 'user status : 1-active, 2-inactive, 3-banned';
COMMENT ON COLUMN users.user_level IS 'user level : 1-admin, 2-moder, 3-member';
COMMENT ON COLUMN users.user_age IS 'user age must be between 1 and 120';
COMMENT ON COLUMN users.user_deleted_at IS 'soft delete timestamp, null if not deleted';

-- create index
CREATE INDEX IF NOT EXISTS idx_users_level ON users(user_level);
CREATE INDEX IF NOT EXISTS idx_users_status ON users(user_status);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(user_created_at);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users(user_deleted_at);
CREATE INDEX IF NOT EXISTS idx_users_email_status ON users(user_email, user_status);

-- create trigger
CREATE OR REPLACE FUNCTION update_user_updated_at()
RETURNS TRIGGER AS $$
BEGIN
	NEW.user_updated_at = NOW();
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_user_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_user_updated_at();