// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
	ListUsersCreateAtAsc(ctx context.Context, arg ListUsersCreateAtAscParams) ([]User, error)
	ListUsersCreateAtDesc(ctx context.Context, arg ListUsersCreateAtDescParams) ([]User, error)
	ListUsersIdAsc(ctx context.Context, arg ListUsersIdAscParams) ([]User, error)
	ListUsersIdDesc(ctx context.Context, arg ListUsersIdDescParams) ([]User, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDeleteUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	TrashUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
