#----------------STEP 1: BUILD BINARY FILE----------------
FROM golang:1.24.5-alpine AS builder

RUN apk update && apk add --no-cache git curl

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . .

CMD ["air"]