-- Lược đồ CSDL PostgreSQL cho CMS - viết lại theo phong cách yêu cầu
-- Tác giả: Gemini - Database Architect
-- Ngày tạo: 26/08/2025
-- Phiên bản: 1.1 (Cập nhật khóa ngoại cho categories)

-- =================================================================
-- I. EXTENSIONS
-- =================================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================
-- II. BẢNG `users`
-- =================================================================
-- CREATE TABLE
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid UUID NOT NULL DEFAULT gen_random_uuid () UNIQUE,
    user_username VARCHAR(50) UNIQUE NOT NULL,
    user_email VARCHAR(255) UNIQUE NOT NULL,
    user_password_hash VARCHAR(255) NOT NULL,
    user_role INT NOT NULL DEFAULT 1 CHECK (user_role IN (1, 2, 3)),
    user_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- COMMENT ON COLUMNS
COMMENT ON COLUMN users.user_role IS 'Vai trò người dùng: 1-user, 2-editor, 3-admin';

COMMENT ON COLUMN users.user_deleted_at IS 'Dùng cho soft delete. NULL = chưa xóa.';

-- CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_users_email ON users (user_email);

CREATE INDEX IF NOT EXISTS idx_users_role ON users (user_role);

CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (user_deleted_at);

-- CREATE TRIGGER FOR `updated_at`
CREATE OR REPLACE FUNCTION update_user_updated_at()
RETURNS TRIGGER AS $$
BEGIN
   NEW.user_updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_user_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION update_user_updated_at();

-- =================================================================
-- III. BẢNG `categories`
-- =================================================================
-- CREATE TABLE
CREATE TABLE IF NOT EXISTS categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_uuid UUID NOT NULL DEFAULT gen_random_uuid () UNIQUE,
    category_name VARCHAR(100) UNIQUE NOT NULL,
    category_slug VARCHAR(100) UNIQUE NOT NULL,
    category_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    category_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories (category_slug);

-- CREATE TRIGGER FOR `updated_at`
CREATE OR REPLACE FUNCTION update_category_updated_at()
RETURNS TRIGGER AS $$
BEGIN
   NEW.category_updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_category_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION update_category_updated_at();

-- =================================================================
-- IV. BẢNG `articles`
-- =================================================================
-- CREATE TABLE
CREATE TABLE IF NOT EXISTS articles (
    article_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_uuid UUID NOT NULL DEFAULT gen_random_uuid () UNIQUE,
    article_author_id INT NOT NULL,
    article_category_id INT NOT NULL,
    article_title VARCHAR(255) NOT NULL,
    article_slug VARCHAR(255) UNIQUE NOT NULL,
    article_content TEXT,
    article_status INT NOT NULL DEFAULT 1 CHECK (article_status IN (1, 2)),
    article_published_at TIMESTAMPTZ DEFAULT NULL,
    article_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    article_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    article_deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- COMMENT ON COLUMNS
COMMENT ON COLUMN articles.article_status IS 'Trạng thái bài viết: 1-draft, 2-published';

COMMENT ON COLUMN articles.article_deleted_at IS 'Dùng cho soft delete.';

-- CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_articles_author_id ON articles (article_author_id);

CREATE INDEX IF NOT EXISTS idx_articles_category_id ON articles (article_category_id);

CREATE INDEX IF NOT EXISTS idx_articles_slug ON articles (article_slug);

CREATE INDEX IF NOT EXISTS idx_articles_status ON articles (article_status);

CREATE INDEX IF NOT EXISTS idx_articles_deleted_at ON articles (article_deleted_at);

-- CREATE TRIGGER FOR `updated_at`
CREATE OR REPLACE FUNCTION update_article_updated_at()
RETURNS TRIGGER AS $$
BEGIN
   NEW.article_updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_article_updated_at
BEFORE UPDATE ON articles
FOR EACH ROW
EXECUTE FUNCTION update_article_updated_at();

-- =================================================================
-- V. BẢNG `comments`
-- =================================================================
-- CREATE TABLE
CREATE TABLE IF NOT EXISTS comments (
    comment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_uuid UUID NOT NULL DEFAULT gen_random_uuid () UNIQUE,
    comment_article_id INT NOT NULL,
    comment_user_id INT NOT NULL,
    comment_content TEXT NOT NULL,
    comment_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    comment_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_comments_article_id ON comments (comment_article_id);

CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments (comment_user_id);

-- CREATE TRIGGER FOR `updated_at`
CREATE OR REPLACE FUNCTION update_comment_updated_at()
RETURNS TRIGGER AS $$
BEGIN
   NEW.comment_updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_comment_updated_at
BEFORE UPDATE ON comments
FOR EACH ROW
EXECUTE FUNCTION update_comment_updated_at();

-- =================================================================
-- VI. BẢNG `notifications`
-- =================================================================
-- CREATE TABLE
CREATE TABLE IF NOT EXISTS notifications (
    notification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_uuid UUID NOT NULL DEFAULT gen_random_uuid () UNIQUE,
    notification_user_id INT NOT NULL,
    notification_content TEXT NOT NULL,
    notification_is_read BOOLEAN NOT NULL DEFAULT false,
    notification_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- CREATE INDEXES
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (notification_user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications (notification_is_read);

-- =================================================================
-- VII. ĐỊNH NGHĨA QUAN HỆ (FOREIGN KEYS)
-- =================================================================
ALTER TABLE articles
ADD CONSTRAINT fk_articles_author FOREIGN KEY (article_author_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE articles
ADD CONSTRAINT fk_articles_category FOREIGN KEY (article_category_id) REFERENCES categories (category_id) ON DELETE RESTRICT;

ALTER TABLE comments
ADD CONSTRAINT fk_comments_article FOREIGN KEY (comment_article_id) REFERENCES articles (article_id) ON DELETE CASCADE;

ALTER TABLE comments
ADD CONSTRAINT fk_comments_user FOREIGN KEY (comment_user_id) REFERENCES users (user_id) ON DELETE CASCADE;

ALTER TABLE notifications
ADD CONSTRAINT fk_notifications_user FOREIGN KEY (notification_user_id) REFERENCES users (user_id) ON DELETE CASCADE;